# This is a basic workflow to help you get started with Actions
name: Test GitUtils

# Controls when the action will run.
on:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Run node script to test getPullRequestsMergedBetween function
        uses: ./ # Uses an action in the root directory
        run: node index.js
