name: Test JavaScript

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Remove version from package-lock.json
              run: jq 'del(.version, .packages[""].version)' package-lock.json > normalized-package-lock.json

            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: npm
                  cache-dependency-path: normalized-package-lock.json

            - run: npm ci

            - run: npm run test
              env:
                  CI: true
